[package]
name = "siweapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
siwe = "0.5"
ethers = "0.17.0"
hex = "0.4"
async-std = { version = "1.10", features = ["attributes"] }

